### ISSUE TITLE
UART stub error

### ISSUE THREAD

**Issue by Goughygough** [cpwood/Pico-Go#39]
## What are the steps to reproduce this issue?
1. Define a UART. e.g. "uart = UART(1,9600)" is structure in Thonny, but not accepted as a valid constructor in VSCode
2.
3.

## What happens?
IDE throws error that UART doesn't accept arguments

## What were you expecting to happen?
UART to accept arguments

## Any logs, error output, etc?

_Expected no arguments to "UART" constructorPylancereportGeneralTypeIssues

Peek Problem (Alt+F8)
No quick fixes available_

## Support info

Copy this from the `Pico-Go > Extra > Get support info` option in the command palette:

```
< Paste Here >
```

**Comment by cpwood** [comment]
Thanks, really appreciate you raising  this.

We're tracking this over in the [Pico-Stub project](https://github.com/cpwood/Pico-Stub/issues/7) and it'll get resolved very soon. I'll close this ticket in the meantime.

I'll also make it more obvious that auto-complete and linting issues should go over there rather than here. Sorry for that not being clearer already.

Best wishes, and thanks again!
